"""Build and cache call-level ASR context profiles (metadata_only).

A *profile* is a short, deduplicated comma-separated keyword list generated by an
LLM from a call's metadata. It is later injected into Whisper as ``initial_prompt``
to softly bias decoding toward the call's domain vocabulary. The list is trimmed to
fit Whisper's ~224-token prompt window so biasing stays effective.
"""

from __future__ import annotations

import os
import re
import time
from datetime import datetime, timezone
from enum import Enum
from functools import lru_cache
from pathlib import Path

from dotenv import load_dotenv
from loguru import logger
from openai import APITimeoutError, OpenAI, RateLimitError
from pydantic import BaseModel

from src.lexical_stylistic_prompting.models.constants import (
    DEFAULT_LLM_MODEL,
    KISSKI_BASE_URL,
    KISSKI_REQUESTS_PER_MINUTE,
    LLM_MAX_RETRIES,
    LLM_RATE_LIMIT_MAX_RETRIES,
    LLM_RETRY_WAIT_SECONDS,
    LLM_TIMEOUT_SECONDS,
    MAX_PROMPT_TERMS,
    MAX_PROMPT_TOKENS,
    MAX_PROMPT_WORDS,
    MAX_WORDS_PER_TERM,
    PROFILES_DIR,
)
from src.lexical_stylistic_prompting.models.prompts import (
    LIST_FORMAT_RULES,
    METADATA_ONLY_SYSTEM,
    METADATA_ONLY_USER,
    PROSE_FORMAT_RULES,
    TRANSCRIPT_METADATA_KNOWLEDGE_SYSTEM,
    TRANSCRIPT_METADATA_KNOWLEDGE_USER,
    TRANSCRIPT_ONLY_SYSTEM,
    TRANSCRIPT_ONLY_USER,
    TRANSCRIPT_PLUS_KNOWLEDGE_SYSTEM,
    TRANSCRIPT_PLUS_KNOWLEDGE_USER,
)

load_dotenv()


class ProfileStrategy(str, Enum):
    METADATA_ONLY = "metadata_only"
    TRANSCRIPT_ONLY = "transcript_only"
    TRANSCRIPT_PLUS_KNOWLEDGE = "transcript_plus_knowledge"
    TRANSCRIPT_METADATA_KNOWLEDGE = "transcript_metadata_knowledge"


class PromptFormat(str, Enum):
    """Surface form of the injected initial_prompt — orthogonal to ProfileStrategy (RQ2.1)."""

    LIST = "list"
    PROSE = "prose"


def profile_subdir(strategy: ProfileStrategy, prompt_format: PromptFormat) -> str:
    """Sub-directory name for a strategy×format combination.

    LIST keeps the historical ``<strategy>`` layout so existing list profiles and their
    eval paths stay valid; PROSE lands in a sibling ``<strategy>_prose`` directory.
    """
    if prompt_format == PromptFormat.LIST:
        return strategy.value
    return f"{strategy.value}_{prompt_format.value}"


class SpeakerProfile(BaseModel):
    speaker_id: str
    n_profile: int
    strategy: ProfileStrategy
    prompt_format: PromptFormat = PromptFormat.LIST
    model: str
    prompt: str
    created_at: str


def _get_client() -> OpenAI:
    api_key = os.environ.get("KISSKI_API_KEY") or os.environ.get("SAIA_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "Set KISSKI_API_KEY or SAIA_API_KEY in your environment or .env file."
        )
    return OpenAI(
        base_url=KISSKI_BASE_URL,
        api_key=api_key,
        timeout=LLM_TIMEOUT_SECONDS,
        max_retries=0,
    )


# Client-side throttle so batch runs stay under KISSKI's per-minute request cap. Shared across
# all callers in the process (single-threaded); enforces a minimum gap between requests.
_MIN_REQUEST_INTERVAL = 60.0 / KISSKI_REQUESTS_PER_MINUTE
_last_request_time = 0.0


def _throttle() -> None:
    global _last_request_time
    wait = _MIN_REQUEST_INTERVAL - (time.monotonic() - _last_request_time)
    if wait > 0:
        time.sleep(wait)
    _last_request_time = time.monotonic()


def _retry_after_seconds(err: RateLimitError) -> float | None:
    """Seconds to wait from a 429's headers (retry-after / ratelimit-reset), if present."""
    response = getattr(err, "response", None)
    headers = getattr(response, "headers", None)
    if not headers:
        return None
    for key in ("retry-after", "ratelimit-reset", "x-ratelimit-reset"):
        value = headers.get(key)
        if value:
            try:
                return float(value) + 1.0  # small buffer past the reset boundary
            except ValueError:
                continue
    return None


def _llm_call(client: OpenAI, model: str, system: str, user: str, max_tokens: int = 160) -> str:
    timeout_attempts = 0
    rate_limit_attempts = 0
    while True:
        _throttle()
        try:
            logger.debug(f"Sending request to KISSKI ({model}) ...")
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                temperature=0.2,
                max_tokens=max_tokens,
                # No frequency penalty: it penalizes the reused comma/space tokens in a
                # list and pushes the model into prose ("clean terms, then a sentence").
                frequency_penalty=0.0,
                timeout=LLM_TIMEOUT_SECONDS,
            )
            content = response.choices[0].message.content
            assert content is not None, "LLM returned empty content"
            return content.strip()
        except APITimeoutError:
            timeout_attempts += 1
            if timeout_attempts >= LLM_MAX_RETRIES:
                raise
            logger.warning(f"KISSKI timed out, retrying in {LLM_RETRY_WAIT_SECONDS}s ...")
            time.sleep(LLM_RETRY_WAIT_SECONDS)
        except RateLimitError as err:
            rate_limit_attempts += 1
            if rate_limit_attempts > LLM_RATE_LIMIT_MAX_RETRIES:
                raise
            wait = _retry_after_seconds(err) or LLM_RETRY_WAIT_SECONDS
            logger.warning(f"KISSKI rate-limited (429), attempt {rate_limit_attempts}/"
                           f"{LLM_RATE_LIMIT_MAX_RETRIES}, waiting {wait:.0f}s ...")
            time.sleep(wait)


@lru_cache(maxsize=1)
def _whisper_tokenizer():
    """Whisper's decoder tokenizer, used to measure the prompt's token length."""
    from whisper.tokenizer import get_tokenizer

    return get_tokenizer(multilingual=True, language="en", task="transcribe")


def _split_terms(raw: str) -> list[str]:
    """Split an LLM response into individual terms, treating newlines as separators."""
    cleaned = raw.replace("\n", ",")
    return [t.strip() for t in re.split(r"\s*,\s*", cleaned) if t.strip()]


def _dedupe(terms: list[str]) -> list[str]:
    """Case-insensitive de-duplication that preserves order and original casing."""
    seen: set[str] = set()
    out: list[str] = []
    for t in terms:
        key = t.lower()
        if key not in seen:
            seen.add(key)
            out.append(t)
    return out


def _fit_token_budget(terms: list[str], max_tokens: int = MAX_PROMPT_TOKENS) -> list[str]:
    """Drop trailing terms until the joined prompt fits within Whisper's prompt window."""
    tokenizer = _whisper_tokenizer()
    kept: list[str] = []
    for term in terms:
        candidate = ", ".join(kept + [term])
        # Whisper prepends a space before the prompt; mirror that when counting.
        if len(tokenizer.encode(" " + candidate)) > max_tokens:
            break
        kept.append(term)
    return kept


def normalize_prompt(raw: str) -> str:
    """Turn a raw LLM response into a clean, deduplicated, budget-fitted keyword list.

    Drops overly long items (prose that slipped past the comma split) before deduping,
    capping the term count, and trimming to Whisper's prompt-token budget.
    """
    terms = [t for t in _split_terms(raw) if len(t.split()) <= MAX_WORDS_PER_TERM]
    terms = _dedupe(terms)[:MAX_PROMPT_TERMS]
    terms = _fit_token_budget(terms)
    return ", ".join(terms)


def _fit_prose_token_budget(text: str, max_tokens: int = MAX_PROMPT_TOKENS) -> str:
    """Drop trailing words until the passage fits within Whisper's prompt window."""
    tokenizer = _whisper_tokenizer()
    kept: list[str] = []
    for word in text.split():
        candidate = " ".join(kept + [word])
        # Whisper prepends a space before the prompt; mirror that when counting.
        if len(tokenizer.encode(" " + candidate)) > max_tokens:
            break
        kept.append(word)
    return " ".join(kept)


def normalize_prose(raw: str) -> str:
    """Turn a raw LLM response into a single clean, budget-fitted prose passage.

    Unlike ``normalize_prompt`` this preserves sentence structure: it only collapses
    whitespace/newlines, strips wrapping quotes the model sometimes adds, and trims to
    Whisper's prompt-token budget — no comma-splitting, deduping, or term capping.
    """
    text = " ".join(raw.split()).strip("\"'")
    return _fit_prose_token_budget(text)


_TRANSCRIPT_PROMPTS = {
    ProfileStrategy.TRANSCRIPT_ONLY: (TRANSCRIPT_ONLY_SYSTEM, TRANSCRIPT_ONLY_USER),
    ProfileStrategy.TRANSCRIPT_PLUS_KNOWLEDGE: (
        TRANSCRIPT_PLUS_KNOWLEDGE_SYSTEM,
        TRANSCRIPT_PLUS_KNOWLEDGE_USER,
    ),
    ProfileStrategy.TRANSCRIPT_METADATA_KNOWLEDGE: (
        TRANSCRIPT_METADATA_KNOWLEDGE_SYSTEM,
        TRANSCRIPT_METADATA_KNOWLEDGE_USER,
    ),
}


def build_profile(
    speaker_id: str,
    strategy: ProfileStrategy,
    n_profile: int,
    company_name: str = "",
    sector: str = "",
    financial_quarter: str = "",
    transcript: str = "",
    n_segments: int = 0,
    prompt_format: PromptFormat = PromptFormat.LIST,
    model: str = DEFAULT_LLM_MODEL,
    client: OpenAI | None = None,
) -> SpeakerProfile:
    if client is None:
        client = _get_client()

    if prompt_format == PromptFormat.PROSE:
        format_rules = PROSE_FORMAT_RULES.format(max_words=MAX_PROMPT_WORDS)
    else:
        format_rules = LIST_FORMAT_RULES.format(max_terms=MAX_PROMPT_TERMS)

    if strategy == ProfileStrategy.METADATA_ONLY:
        user_msg = METADATA_ONLY_USER.format(
            company_name=company_name,
            sector=sector,
            financial_quarter=financial_quarter,
            format_rules=format_rules,
        )
        raw = _llm_call(client, model, METADATA_ONLY_SYSTEM, user_msg)
    elif strategy in _TRANSCRIPT_PROMPTS:
        if not transcript.strip():
            raise ValueError(f"{strategy.value} requires a non-empty transcript")
        system, user_template = _TRANSCRIPT_PROMPTS[strategy]
        user_msg = user_template.format(
            n_segments=n_segments,
            transcript=transcript,
            company_name=company_name,
            sector=sector,
            financial_quarter=financial_quarter,
            format_rules=format_rules,
        )
        raw = _llm_call(client, model, system, user_msg)
    else:
        raise ValueError(f"Unknown strategy: {strategy}")

    prompt = normalize_prose(raw) if prompt_format == PromptFormat.PROSE else normalize_prompt(raw)
    return SpeakerProfile(
        speaker_id=speaker_id,
        n_profile=n_profile,
        strategy=strategy,
        prompt_format=prompt_format,
        model=model,
        prompt=prompt,
        created_at=datetime.now(timezone.utc).isoformat(),
    )


def save_profile(profile: SpeakerProfile, profiles_dir: Path = PROFILES_DIR) -> Path:
    out_dir = profiles_dir / profile_subdir(profile.strategy, profile.prompt_format)
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{profile.speaker_id}_{profile.n_profile}.json"
    out.write_text(profile.model_dump_json(indent=2))
    logger.info(f"Saved profile → {out}")
    return out


def load_profile(
    speaker_id: str,
    n_profile: int,
    strategy: ProfileStrategy,
    profiles_dir: Path = PROFILES_DIR,
    prompt_format: PromptFormat = PromptFormat.LIST,
) -> SpeakerProfile:
    path = profiles_dir / profile_subdir(strategy, prompt_format) / f"{speaker_id}_{n_profile}.json"
    return SpeakerProfile.model_validate_json(path.read_text())

