"""Build and cache call-level ASR context profiles (metadata_only).

A *profile* is a short, deduplicated comma-separated keyword list generated by an
LLM from a call's metadata. It is later injected into Whisper as ``initial_prompt``
to softly bias decoding toward the call's domain vocabulary. The list is trimmed to
fit Whisper's ~224-token prompt window so biasing stays effective.
"""

from __future__ import annotations

import os
import re
import time
from datetime import datetime, timezone
from enum import Enum
from functools import lru_cache
from pathlib import Path

from dotenv import load_dotenv
from loguru import logger
from openai import APITimeoutError, OpenAI
from pydantic import BaseModel

from src.lexical_stylistic_prompting.models.constants import (
    DEFAULT_LLM_MODEL,
    KISSKI_BASE_URL,
    LLM_MAX_RETRIES,
    LLM_RETRY_WAIT_SECONDS,
    LLM_TIMEOUT_SECONDS,
    MAX_PROMPT_TERMS,
    MAX_PROMPT_TOKENS,
    MAX_WORDS_PER_TERM,
    PROFILES_DIR,
)
from src.lexical_stylistic_prompting.models.prompts import (
    METADATA_ONLY_SYSTEM,
    METADATA_ONLY_USER,
)

load_dotenv()


class ProfileStrategy(str, Enum):
    METADATA_ONLY = "metadata_only"


class SpeakerProfile(BaseModel):
    speaker_id: str
    n_profile: int
    strategy: ProfileStrategy
    model: str
    prompt: str
    created_at: str


def _get_client() -> OpenAI:
    api_key = os.environ.get("KISSKI_API_KEY") or os.environ.get("SAIA_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "Set KISSKI_API_KEY or SAIA_API_KEY in your environment or .env file."
        )
    return OpenAI(
        base_url=KISSKI_BASE_URL,
        api_key=api_key,
        timeout=LLM_TIMEOUT_SECONDS,
        max_retries=0,
    )


def _llm_call(client: OpenAI, model: str, system: str, user: str) -> str:
    for attempt in range(1, LLM_MAX_RETRIES + 1):
        try:
            logger.info(f"Sending request to KISSKI ({model}), attempt {attempt}/{LLM_MAX_RETRIES} ...")
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user", "content": user},
                ],
                temperature=0.2,
                max_tokens=160,
                # No frequency penalty: it penalizes the reused comma/space tokens in a
                # list and pushes the model into prose ("clean terms, then a sentence").
                frequency_penalty=0.0,
                timeout=LLM_TIMEOUT_SECONDS,
            )
            content = response.choices[0].message.content
            assert content is not None, "LLM returned empty content"
            return content.strip()
        except APITimeoutError:
            if attempt == LLM_MAX_RETRIES:
                raise
            logger.warning(f"KISSKI timed out, retrying in {LLM_RETRY_WAIT_SECONDS}s ...")
            time.sleep(LLM_RETRY_WAIT_SECONDS)
    raise RuntimeError("unreachable")


@lru_cache(maxsize=1)
def _whisper_tokenizer():
    """Whisper's decoder tokenizer, used to measure the prompt's token length."""
    from whisper.tokenizer import get_tokenizer

    return get_tokenizer(multilingual=True, language="en", task="transcribe")


def _split_terms(raw: str) -> list[str]:
    """Split an LLM response into individual terms, treating newlines as separators."""
    cleaned = raw.replace("\n", ",")
    return [t.strip() for t in re.split(r"\s*,\s*", cleaned) if t.strip()]


def _dedupe(terms: list[str]) -> list[str]:
    """Case-insensitive de-duplication that preserves order and original casing."""
    seen: set[str] = set()
    out: list[str] = []
    for t in terms:
        key = t.lower()
        if key not in seen:
            seen.add(key)
            out.append(t)
    return out


def _fit_token_budget(terms: list[str], max_tokens: int = MAX_PROMPT_TOKENS) -> list[str]:
    """Drop trailing terms until the joined prompt fits within Whisper's prompt window."""
    tokenizer = _whisper_tokenizer()
    kept: list[str] = []
    for term in terms:
        candidate = ", ".join(kept + [term])
        # Whisper prepends a space before the prompt; mirror that when counting.
        if len(tokenizer.encode(" " + candidate)) > max_tokens:
            break
        kept.append(term)
    return kept


def normalize_prompt(raw: str) -> str:
    """Turn a raw LLM response into a clean, deduplicated, budget-fitted keyword list.

    Drops overly long items (prose that slipped past the comma split) before deduping,
    capping the term count, and trimming to Whisper's prompt-token budget.
    """
    terms = [t for t in _split_terms(raw) if len(t.split()) <= MAX_WORDS_PER_TERM]
    terms = _dedupe(terms)[:MAX_PROMPT_TERMS]
    terms = _fit_token_budget(terms)
    return ", ".join(terms)


def build_profile(
    speaker_id: str,
    strategy: ProfileStrategy,
    n_profile: int,
    company_name: str = "",
    sector: str = "",
    financial_quarter: str = "",
    model: str = DEFAULT_LLM_MODEL,
    client: OpenAI | None = None,
) -> SpeakerProfile:
    if client is None:
        client = _get_client()

    if strategy == ProfileStrategy.METADATA_ONLY:
        user_msg = METADATA_ONLY_USER.format(
            company_name=company_name,
            sector=sector,
            financial_quarter=financial_quarter,
            max_terms=MAX_PROMPT_TERMS,
        )
        raw = _llm_call(client, model, METADATA_ONLY_SYSTEM, user_msg)
    else:
        raise ValueError(f"Unknown strategy: {strategy}")

    prompt = normalize_prompt(raw)
    return SpeakerProfile(
        speaker_id=speaker_id,
        n_profile=n_profile,
        strategy=strategy,
        model=model,
        prompt=prompt,
        created_at=datetime.now(timezone.utc).isoformat(),
    )


def save_profile(profile: SpeakerProfile, profiles_dir: Path = PROFILES_DIR) -> Path:
    out_dir = profiles_dir / profile.strategy.value
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{profile.speaker_id}_{profile.n_profile}.json"
    out.write_text(profile.model_dump_json(indent=2))
    logger.info(f"Saved profile → {out}")
    return out


def load_profile(
    speaker_id: str,
    n_profile: int,
    strategy: ProfileStrategy,
    profiles_dir: Path = PROFILES_DIR,
) -> SpeakerProfile:
    path = profiles_dir / strategy.value / f"{speaker_id}_{n_profile}.json"
    return SpeakerProfile.model_validate_json(path.read_text())

